
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/my-next-app'
    - '--build-arg'
    - 'ADMIN_PROJECT_ID=${_ADMIN_PROJECT_ID}'
    - '--build-arg'
    - 'ADMIN_PRIVATE_KEY=${_ADMIN_PRIVATE_KEY}'
    - '--build-arg'
    - 'ADMIN_CLIENT_EMAIL=${_ADMIN_CLIENT_EMAIL}'
    

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-next-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-next-app'
      - '--image=gcr.io/$PROJECT_ID/my-next-app'
      - '--platform=managed'
      - '--timeout=1000s'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=ADMIN_PROJECT_ID=${_ADMIN_PROJECT_ID},ADMIN_PRIVATE_KEY=${_ADMIN_PRIVATE_KEY},ADMIN_CLIENT_EMAIL=${_ADMIN_CLIENT_EMAIL}'

options:
  logging: CLOUD_LOGGING_ONLY
